# Generated by Django 3.1 on 2020-08-09 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('currency_type', models.CharField(choices=[('eur', 'eur'), ('usd', 'usd'), ('gpb', 'gpb'), ('rub', 'rub'), ('btc', 'btc')], max_length=3, verbose_name='Тип валюты')),
                ('balance_amount', models.IntegerField(default=0, verbose_name='Сумма баланса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currencies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Валюта счета',
                'verbose_name_plural': 'Валюты счетов',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('transfer_amount', models.PositiveIntegerField(verbose_name='Сумма перевода')),
                ('recipient_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='payments.accountcurrency', verbose_name='Счет получателя')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='payments.accountcurrency', verbose_name='Счет отправителя')),
            ],
            options={
                'verbose_name': 'Платежная транзакция',
                'verbose_name_plural': 'Платежные транзакции',
            },
        ),
    ]
