# Generated by Django 3.1 on 2020-08-09 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_accountcurrency_paymenttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('payment_type', models.CharField(choices=[('add', 'Пополнение'), ('debit', 'Списание')], max_length=5, verbose_name='Тип перевода')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='payments.paymenttransaction', verbose_name='Платежная транзакция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История операций',
                'verbose_name_plural': 'История операций',
            },
        ),
    ]
