# Generated by Django 3.1 on 2020-08-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_usertransactionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('symbol', models.CharField(choices=[('€', '€'), ('$', '$'), ('£', '£'), ('руб.', 'руб.'), ('₿', '₿')], max_length=5, verbose_name='Символ')),
                ('multiplicity', models.PositiveIntegerField(verbose_name='Кратность')),
                ('rate', models.FloatField(verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.AddField(
            model_name='accountcurrency',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='payments.currency', verbose_name='Валюта'),
        ),
    ]
