# Generated by Django 3.1 on 2020-08-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200809_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcurrency',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='payments.currency', verbose_name='Валюта'),
        ),
    ]
