# Generated by Django 3.1 on 2020-08-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20200809_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcurrency',
            name='currency_type',
            field=models.CharField(choices=[('eur', 'eur'), ('usd', 'usd'), ('gpb', 'gpb'), ('rub', 'rub'), ('btc', 'btc')], max_length=3, null=True, verbose_name='Тип валюты'),
        ),
    ]
