# Generated by Django 3.1 on 2020-08-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20200809_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountcurrency',
            name='currency_type',
        ),
    ]
