# Generated by Django 3.1 on 2020-08-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20200809_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransactionhistory',
            name='transfer_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Сумма перевода'),
        ),
    ]
