# Generated by Django 3.1 on 2020-08-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20200809_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='transfer_amount',
        ),
    ]
