# Generated by Django 3.1 on 2020-08-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_remove_paymenttransaction_transfer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcurrency',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма баланса'),
        ),
    ]
